/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import java.awt.Color;
import models.User;
import models.Users;
/**
 *
 * @author fatur ++
 */
public class Dashboard extends javax.swing.JFrame {

    
    public Dashboard() {
        initComponents();
        displayUserInfo();
        panelUtama.removeAll();
        panelUtama.add(new Beranda());
        panelUtama.repaint();
        panelUtama.revalidate();
    }
    private void displayUserInfo() {
        User user = Session.getInstance().getUser();
        if (user != null) {
            lblUsername.setText("Username: " + user.getUsername());
            lblUserId.setText("User ID: " + user.getId());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoDInus = new javax.swing.JLabel();
        panelBeranda = new javax.swing.JPanel();
        pnLine = new javax.swing.JPanel();
        iconBeranda = new javax.swing.JLabel();
        beranda = new javax.swing.JLabel();
        panelBiodata = new javax.swing.JPanel();
        pnLine2 = new javax.swing.JPanel();
        iconBiodata = new javax.swing.JLabel();
        biodata = new javax.swing.JLabel();
        panelPendaftaran = new javax.swing.JPanel();
        pnLine3 = new javax.swing.JPanel();
        iconPendaftaran = new javax.swing.JLabel();
        pendaftaran = new javax.swing.JLabel();
        panelPrestasi = new javax.swing.JPanel();
        pnLine4 = new javax.swing.JPanel();
        iconPrestasi = new javax.swing.JLabel();
        prestasi = new javax.swing.JLabel();
        panelPembayaran = new javax.swing.JPanel();
        pnLine5 = new javax.swing.JPanel();
        IconPembayaran = new javax.swing.JLabel();
        pembayaran = new javax.swing.JLabel();
        panelFinalisasi = new javax.swing.JPanel();
        pnLine6 = new javax.swing.JPanel();
        iconFinalisasi = new javax.swing.JLabel();
        finalisasi = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        pnLine7 = new javax.swing.JPanel();
        iconLogout = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        panelInformasi = new javax.swing.JPanel();
        pnLine8 = new javax.swing.JPanel();
        iconinformasi = new javax.swing.JLabel();
        informasi = new javax.swing.JLabel();
        panelKanan = new javax.swing.JPanel();
        panelAtas = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        panalDasar = new javax.swing.JPanel();
        panelUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoDInus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo-Web-Biru-1280x260.png"))); // NOI18N

        panelBeranda.setBackground(new java.awt.Color(240, 240, 240));
        panelBeranda.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                panelBerandaComponentAdded(evt);
            }
        });
        panelBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBerandaMouseExited(evt);
            }
        });

        pnLine.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pnLineLayout = new javax.swing.GroupLayout(pnLine);
        pnLine.setLayout(pnLineLayout);
        pnLineLayout.setHorizontalGroup(
            pnLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLineLayout.setVerticalGroup(
            pnLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_icon-icons.com_73532.png"))); // NOI18N
        iconBeranda.setText("jLabel2");
        iconBeranda.setPreferredSize(new java.awt.Dimension(40, 40));
        iconBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconBerandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconBerandaMouseExited(evt);
            }
        });

        beranda.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        beranda.setText("Beranda");
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                berandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                berandaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBerandaLayout = new javax.swing.GroupLayout(panelBeranda);
        panelBeranda.setLayout(panelBerandaLayout);
        panelBerandaLayout.setHorizontalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelBerandaLayout.setVerticalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(beranda)
                    .addComponent(pnLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelBiodata.setBackground(new java.awt.Color(240, 240, 240));
        panelBiodata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBiodataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBiodataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBiodataMouseExited(evt);
            }
        });

        pnLine2.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pnLine2Layout = new javax.swing.GroupLayout(pnLine2);
        pnLine2.setLayout(pnLine2Layout);
        pnLine2Layout.setHorizontalGroup(
            pnLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine2Layout.setVerticalGroup(
            pnLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconBiodata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/biodata_resume_job_application_profile_cv_vitae_curriculum_icon_232605.png"))); // NOI18N
        iconBiodata.setText("jLabel2");
        iconBiodata.setPreferredSize(new java.awt.Dimension(40, 40));
        iconBiodata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconBiodataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconBiodataMouseExited(evt);
            }
        });

        biodata.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        biodata.setText("Biodata");
        biodata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biodataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                biodataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                biodataMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBiodataLayout = new javax.swing.GroupLayout(panelBiodata);
        panelBiodata.setLayout(panelBiodataLayout);
        panelBiodataLayout.setHorizontalGroup(
            panelBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiodataLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconBiodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(biodata, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelBiodataLayout.setVerticalGroup(
            panelBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiodataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBiodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconBiodata, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(biodata)
                    .addComponent(pnLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelPendaftaran.setBackground(new java.awt.Color(240, 240, 240));
        panelPendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPendaftaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPendaftaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPendaftaranMouseExited(evt);
            }
        });

        pnLine3.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pnLine3Layout = new javax.swing.GroupLayout(pnLine3);
        pnLine3.setLayout(pnLine3Layout);
        pnLine3Layout.setHorizontalGroup(
            pnLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine3Layout.setVerticalGroup(
            pnLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/writing-tools-symbol-of-interface-with-black-square-paper-note-and-a-pencil_icon-icons.com_72884.png"))); // NOI18N
        iconPendaftaran.setText("jLabel2");
        iconPendaftaran.setPreferredSize(new java.awt.Dimension(40, 40));
        iconPendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconPendaftaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconPendaftaranMouseExited(evt);
            }
        });

        pendaftaran.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pendaftaran.setText("Pendaftaran");
        pendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pendaftaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pendaftaranMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelPendaftaranLayout = new javax.swing.GroupLayout(panelPendaftaran);
        panelPendaftaran.setLayout(panelPendaftaranLayout);
        panelPendaftaranLayout.setHorizontalGroup(
            panelPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPendaftaranLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelPendaftaranLayout.setVerticalGroup(
            panelPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPendaftaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPendaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconPendaftaran, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(pendaftaran)
                    .addComponent(pnLine3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelPrestasi.setBackground(new java.awt.Color(240, 240, 240));
        panelPrestasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPrestasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPrestasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPrestasiMouseExited(evt);
            }
        });

        pnLine4.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pnLine4Layout = new javax.swing.GroupLayout(pnLine4);
        pnLine4.setLayout(pnLine4Layout);
        pnLine4Layout.setHorizontalGroup(
            pnLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine4Layout.setVerticalGroup(
            pnLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconPrestasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thropy_cup_winner_medal_sport_icon_228549.png"))); // NOI18N
        iconPrestasi.setText("jLabel2");
        iconPrestasi.setPreferredSize(new java.awt.Dimension(40, 40));
        iconPrestasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconPrestasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconPrestasiMouseExited(evt);
            }
        });

        prestasi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        prestasi.setText("Prestasi");
        prestasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prestasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prestasiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelPrestasiLayout = new javax.swing.GroupLayout(panelPrestasi);
        panelPrestasi.setLayout(panelPrestasiLayout);
        panelPrestasiLayout.setHorizontalGroup(
            panelPrestasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestasiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconPrestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelPrestasiLayout.setVerticalGroup(
            panelPrestasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrestasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconPrestasi, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(prestasi)
                    .addComponent(pnLine4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelPembayaran.setBackground(new java.awt.Color(240, 240, 240));
        panelPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPembayaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPembayaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPembayaranMouseExited(evt);
            }
        });

        pnLine5.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pnLine5Layout = new javax.swing.GroupLayout(pnLine5);
        pnLine5.setLayout(pnLine5Layout);
        pnLine5Layout.setHorizontalGroup(
            pnLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine5Layout.setVerticalGroup(
            pnLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        IconPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dollar-coin-money_icon-icons.com_56177.png"))); // NOI18N
        IconPembayaran.setText("jLabel2");
        IconPembayaran.setPreferredSize(new java.awt.Dimension(40, 40));
        IconPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconPembayaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconPembayaranMouseExited(evt);
            }
        });

        pembayaran.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pembayaran.setText("Pembayaran");
        pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pembayaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pembayaranMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelPembayaranLayout = new javax.swing.GroupLayout(panelPembayaran);
        panelPembayaran.setLayout(panelPembayaranLayout);
        panelPembayaranLayout.setHorizontalGroup(
            panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembayaranLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnLine5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IconPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelPembayaranLayout.setVerticalGroup(
            panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IconPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(pembayaran)
                    .addComponent(pnLine5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelFinalisasi.setBackground(new java.awt.Color(240, 240, 240));
        panelFinalisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFinalisasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFinalisasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFinalisasiMouseExited(evt);
            }
        });

        pnLine6.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pnLine6Layout = new javax.swing.GroupLayout(pnLine6);
        pnLine6.setLayout(pnLine6Layout);
        pnLine6Layout.setHorizontalGroup(
            pnLine6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine6Layout.setVerticalGroup(
            pnLine6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconFinalisasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black-check-box-with-white-check_icon-icons.com_72859.png"))); // NOI18N
        iconFinalisasi.setText("jLabel2");
        iconFinalisasi.setPreferredSize(new java.awt.Dimension(40, 40));
        iconFinalisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconFinalisasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconFinalisasiMouseExited(evt);
            }
        });

        finalisasi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        finalisasi.setText("FInalisasi");
        finalisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finalisasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finalisasiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelFinalisasiLayout = new javax.swing.GroupLayout(panelFinalisasi);
        panelFinalisasi.setLayout(panelFinalisasiLayout);
        panelFinalisasiLayout.setHorizontalGroup(
            panelFinalisasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalisasiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnLine6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconFinalisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finalisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelFinalisasiLayout.setVerticalGroup(
            panelFinalisasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalisasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinalisasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconFinalisasi, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(finalisasi)
                    .addComponent(pnLine6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelLogout.setBackground(new java.awt.Color(240, 240, 240));
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogoutMouseExited(evt);
            }
        });

        pnLine7.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pnLine7Layout = new javax.swing.GroupLayout(pnLine7);
        pnLine7.setLayout(pnLine7Layout);
        pnLine7Layout.setHorizontalGroup(
            pnLine7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine7Layout.setVerticalGroup(
            pnLine7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/power_on_off_log_out_exit_icon_141949.png"))); // NOI18N
        iconLogout.setText("jLabel2");
        iconLogout.setPreferredSize(new java.awt.Dimension(40, 40));
        iconLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconLogoutMouseExited(evt);
            }
        });

        logout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnLine7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(logout)
                    .addComponent(pnLine7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelInformasi.setBackground(new java.awt.Color(240, 240, 240));
        panelInformasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelInformasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelInformasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelInformasiMouseExited(evt);
            }
        });

        pnLine8.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pnLine8Layout = new javax.swing.GroupLayout(pnLine8);
        pnLine8.setLayout(pnLine8Layout);
        pnLine8Layout.setHorizontalGroup(
            pnLine8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine8Layout.setVerticalGroup(
            pnLine8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        iconinformasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info_information_icon_178159.png"))); // NOI18N
        iconinformasi.setText("jLabel2");
        iconinformasi.setPreferredSize(new java.awt.Dimension(40, 40));
        iconinformasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconinformasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconinformasiMouseExited(evt);
            }
        });

        informasi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        informasi.setText("Informasi");
        informasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                informasiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelInformasiLayout = new javax.swing.GroupLayout(panelInformasi);
        panelInformasi.setLayout(panelInformasiLayout);
        panelInformasiLayout.setHorizontalGroup(
            panelInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformasiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnLine8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconinformasi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(informasi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelInformasiLayout.setVerticalGroup(
            panelInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconinformasi, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(informasi)
                    .addComponent(pnLine8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoDInus)
                    .addComponent(panelBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBiodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPrestasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFinalisasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelInformasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKiriLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(panelKiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoDInus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(panelBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBiodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrestasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFinalisasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInformasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(panelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(panelKiri, java.awt.BorderLayout.LINE_START);

        panelKanan.setLayout(new java.awt.BorderLayout());

        panelAtas.setBackground(new java.awt.Color(0, 0, 255));

        lblUsername.setBackground(new java.awt.Color(255, 255, 255));
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("jLabel2");

        lblUserId.setForeground(new java.awt.Color(255, 255, 255));
        lblUserId.setText("jLabel2");

        javax.swing.GroupLayout panelAtasLayout = new javax.swing.GroupLayout(panelAtas);
        panelAtas.setLayout(panelAtasLayout);
        panelAtasLayout.setHorizontalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtasLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(lblUsername)
                .addGap(145, 145, 145)
                .addComponent(lblUserId)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        panelAtasLayout.setVerticalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtasLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(lblUserId))
                .addContainerGap())
        );

        panelKanan.add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panalDasar.setBackground(new java.awt.Color(250, 250, 250));

        panelUtama.setRequestFocusEnabled(false);
        panelUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panalDasarLayout = new javax.swing.GroupLayout(panalDasar);
        panalDasar.setLayout(panalDasarLayout);
        panalDasarLayout.setHorizontalGroup(
            panalDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalDasarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        panalDasarLayout.setVerticalGroup(
            panalDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalDasarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        panelKanan.add(panalDasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelKanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseEntered
        beranda.setBackground(new Color(191, 191, 191));
        panelBeranda.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_berandaMouseEntered

    private void panelBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBerandaMouseEntered
        beranda.setBackground(new Color(191, 191, 191));
        panelBeranda.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_panelBerandaMouseEntered

    private void panelBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBerandaMouseExited
        beranda.setBackground(new Color(242,242,242));
        panelBeranda.setBackground(new Color(242,242,242));
        pnLine.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_panelBerandaMouseExited

    private void berandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseExited
        beranda.setBackground(new Color(242,242,242));
        panelBeranda.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_berandaMouseExited

    private void iconBerandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBerandaMouseExited
        beranda.setBackground(new Color(242,242,242));
        panelBeranda.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_iconBerandaMouseExited

    private void iconPendaftaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPendaftaranMouseExited
        pendaftaran.setBackground(new Color(242,242,242));
        panelPendaftaran.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_iconPendaftaranMouseExited

    private void pendaftaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendaftaranMouseEntered
        pendaftaran.setBackground(new Color(191, 191, 191));
        panelPendaftaran.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_pendaftaranMouseEntered

    private void pendaftaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendaftaranMouseExited
        pendaftaran.setBackground(new Color(242,242,242));
        panelPendaftaran.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_pendaftaranMouseExited

    private void panelPendaftaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPendaftaranMouseEntered
        pendaftaran.setBackground(new Color(191, 191, 191));
        panelPendaftaran.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_panelPendaftaranMouseEntered

    private void panelPendaftaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPendaftaranMouseExited
        pendaftaran.setBackground(new Color(242,242,242));
        panelPendaftaran.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_panelPendaftaranMouseExited

    private void iconPrestasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPrestasiMouseExited
        prestasi.setBackground(new Color(242,242,242));
        panelPrestasi.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_iconPrestasiMouseExited

    private void prestasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestasiMouseEntered
        prestasi.setBackground(new Color(191, 191, 191));
        panelPrestasi.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_prestasiMouseEntered

    private void prestasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestasiMouseExited
        prestasi.setBackground(new Color(242,242,242));
        panelPrestasi.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_prestasiMouseExited

    private void panelPrestasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPrestasiMouseEntered
        prestasi.setBackground(new Color(191, 191, 191));
        panelPrestasi.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_panelPrestasiMouseEntered

    private void panelPrestasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPrestasiMouseExited
        prestasi.setBackground(new Color(242,242,242));
        panelPrestasi.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_panelPrestasiMouseExited

    private void IconPembayaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconPembayaranMouseExited
        pembayaran.setBackground(new Color(242,242,242));
        panelPembayaran.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_IconPembayaranMouseExited

    private void pembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembayaranMouseEntered
        pembayaran.setBackground(new Color(191, 191, 191));
        panelPembayaran.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_pembayaranMouseEntered

    private void pembayaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembayaranMouseExited
        pembayaran.setBackground(new Color(242,242,242));
        panelPembayaran.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_pembayaranMouseExited

    private void panelPembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPembayaranMouseEntered
        pembayaran.setBackground(new Color(191, 191, 191));
        panelPembayaran.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_panelPembayaranMouseEntered

    private void panelPembayaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPembayaranMouseExited
        pembayaran.setBackground(new Color(242,242,242));
        panelPembayaran.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_panelPembayaranMouseExited

    private void iconFinalisasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconFinalisasiMouseExited
        finalisasi.setBackground(new Color(242,242,242));
        panelFinalisasi.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_iconFinalisasiMouseExited

    private void finalisasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalisasiMouseEntered
        finalisasi.setBackground(new Color(191, 191, 191));
        panelFinalisasi.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_finalisasiMouseEntered

    private void finalisasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalisasiMouseExited
        finalisasi.setBackground(new Color(242,242,242));
        panelFinalisasi.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_finalisasiMouseExited

    private void panelFinalisasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFinalisasiMouseEntered
        finalisasi.setBackground(new Color(191, 191, 191));
        panelFinalisasi.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_panelFinalisasiMouseEntered

    private void panelFinalisasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFinalisasiMouseExited
        finalisasi.setBackground(new Color(242,242,242));
        panelFinalisasi.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_panelFinalisasiMouseExited

    private void iconLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLogoutMouseExited
       logout.setBackground(new Color(242,242,242));
        panelLogout.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_iconLogoutMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(new Color(230, 0, 0));
        panelLogout.setBackground(new Color(230, 0, 0));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(new Color(242,242,242));
        panelLogout.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_logoutMouseExited

    private void panelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseEntered
        logout.setBackground(new Color(230, 0, 0));
        panelLogout.setBackground(new Color(230, 0, 0));
    }//GEN-LAST:event_panelLogoutMouseEntered

    private void panelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseExited
        logout.setBackground(new Color(242,242,242));
        panelLogout.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_panelLogoutMouseExited

    private void iconinformasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconinformasiMouseExited
        informasi.setBackground(new Color(242,242,242));
        panelInformasi.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_iconinformasiMouseExited

    private void informasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informasiMouseEntered
        informasi.setBackground(new Color(191, 191, 191));
        panelInformasi.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_informasiMouseEntered

    private void informasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informasiMouseExited
        informasi.setBackground(new Color(242,242,242));
        panelInformasi.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_informasiMouseExited

    private void panelInformasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInformasiMouseEntered
        informasi.setBackground(new Color(191, 191, 191));
        panelInformasi.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_panelInformasiMouseEntered

    private void panelInformasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInformasiMouseExited
        informasi.setBackground(new Color(242,242,242));
        panelInformasi.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_panelInformasiMouseExited

    private void panelBiodataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBiodataMouseExited
        biodata.setBackground(new Color(242,242,242));
        panelBiodata.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_panelBiodataMouseExited

    private void panelBiodataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBiodataMouseEntered
        biodata.setBackground(new Color(191, 191, 191));
        panelBiodata.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_panelBiodataMouseEntered

    private void biodataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biodataMouseExited
        biodata.setBackground(new Color(191, 191, 191));
        panelBiodata.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_biodataMouseExited

    private void biodataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biodataMouseEntered
        biodata.setBackground(new Color(191, 191, 191));
        panelBiodata.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_biodataMouseEntered

    private void iconBiodataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBiodataMouseExited
        biodata.setBackground(new Color(191, 191, 191));
        panelBiodata.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_iconBiodataMouseExited

    private void panelBerandaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_panelBerandaComponentAdded

    }//GEN-LAST:event_panelBerandaComponentAdded

    private void iconBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBerandaMouseEntered
        beranda.setBackground(new Color(191, 191, 191));
        panelBeranda.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_iconBerandaMouseEntered

    private void iconBiodataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBiodataMouseEntered
        biodata.setBackground(new Color(191, 191, 191));
        panelBiodata.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_iconBiodataMouseEntered

    private void iconPendaftaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPendaftaranMouseEntered
        pendaftaran.setBackground(new Color(191, 191, 191));
        panelPendaftaran.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_iconPendaftaranMouseEntered

    private void iconPrestasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPrestasiMouseEntered
        prestasi.setBackground(new Color(191, 191, 191));
        panelPrestasi.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_iconPrestasiMouseEntered

    private void IconPembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconPembayaranMouseEntered
        pembayaran.setBackground(new Color(191, 191, 191));
        panelPembayaran.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_IconPembayaranMouseEntered

    private void iconFinalisasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconFinalisasiMouseEntered
        finalisasi.setBackground(new Color(191, 191, 191));
        panelFinalisasi.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_iconFinalisasiMouseEntered

    private void iconinformasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconinformasiMouseEntered
        informasi.setBackground(new Color(191, 191, 191));
        panelInformasi.setBackground(new Color(191, 191, 191));
    }//GEN-LAST:event_iconinformasiMouseEntered

    private void iconLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLogoutMouseEntered
        logout.setBackground(new Color(255, 0, 0));
        panelLogout.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_iconLogoutMouseEntered

    private void biodataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biodataMouseClicked
        biodata.setBackground(new Color(89, 89, 89));
        panelBiodata.setBackground(new Color(89, 89, 89));
        
        panelUtama.removeAll();
        panelUtama.add(new Beranda());
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_biodataMouseClicked

    private void panelBiodataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBiodataMouseClicked
        biodata.setBackground(new Color(89, 89, 89));
        panelBiodata.setBackground(new Color(89, 89, 89));
        panelUtama.removeAll();
        panelUtama.add(new Biodata());
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelBiodataMouseClicked

    private void panelBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBerandaMouseClicked
        beranda.setBackground(new Color(89, 89, 89));
        panelBeranda.setBackground(new Color(89, 89, 89));
        
        panelUtama.removeAll();
        panelUtama.add(new Beranda());
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelBerandaMouseClicked

    private void panelPendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPendaftaranMouseClicked
        beranda.setBackground(new Color(89, 89, 89));
        panelBeranda.setBackground(new Color(89, 89, 89));
        
        panelUtama.removeAll();
        panelUtama.add(new Pendaftaran());
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelPendaftaranMouseClicked

    private void panelPrestasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPrestasiMouseClicked
        beranda.setBackground(new Color(89, 89, 89));
        panelBeranda.setBackground(new Color(89, 89, 89));
        
        panelUtama.removeAll();
        panelUtama.add(new Prestasi());
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelPrestasiMouseClicked

    private void panelPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPembayaranMouseClicked
        beranda.setBackground(new Color(89, 89, 89));
        panelBeranda.setBackground(new Color(89, 89, 89));
        
        panelUtama.removeAll();
        panelUtama.add(new Pembayaran());
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelPembayaranMouseClicked

    private void panelFinalisasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFinalisasiMouseClicked
        beranda.setBackground(new Color(89, 89, 89));
        panelBeranda.setBackground(new Color(89, 89, 89));
        
        panelUtama.removeAll();
        panelUtama.add(new Finalisasi());
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelFinalisasiMouseClicked

    private void panelInformasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInformasiMouseClicked
        beranda.setBackground(new Color(89, 89, 89));
        panelBeranda.setBackground(new Color(89, 89, 89));
        
        panelUtama.removeAll();
        panelUtama.add(new Informasi());
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_panelInformasiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconPembayaran;
    private javax.swing.JLabel beranda;
    private javax.swing.JLabel biodata;
    private javax.swing.JLabel finalisasi;
    private javax.swing.JLabel iconBeranda;
    private javax.swing.JLabel iconBiodata;
    private javax.swing.JLabel iconFinalisasi;
    private javax.swing.JLabel iconLogout;
    private javax.swing.JLabel iconPendaftaran;
    private javax.swing.JLabel iconPrestasi;
    private javax.swing.JLabel iconinformasi;
    private javax.swing.JLabel informasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel logoDInus;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panalDasar;
    private javax.swing.JPanel panelAtas;
    private javax.swing.JPanel panelBeranda;
    private javax.swing.JPanel panelBiodata;
    private javax.swing.JPanel panelFinalisasi;
    private javax.swing.JPanel panelInformasi;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelPembayaran;
    private javax.swing.JPanel panelPendaftaran;
    private javax.swing.JPanel panelPrestasi;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JLabel pembayaran;
    private javax.swing.JLabel pendaftaran;
    private javax.swing.JPanel pnLine;
    private javax.swing.JPanel pnLine2;
    private javax.swing.JPanel pnLine3;
    private javax.swing.JPanel pnLine4;
    private javax.swing.JPanel pnLine5;
    private javax.swing.JPanel pnLine6;
    private javax.swing.JPanel pnLine7;
    private javax.swing.JPanel pnLine8;
    private javax.swing.JLabel prestasi;
    // End of variables declaration//GEN-END:variables
}
