/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;
import java.sql.*;
import javax.swing.JOptionPane;
import models.User;
/**
 *
 * @author fatur
 */
public class Prestasi extends javax.swing.JPanel {
    
    public static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    public static final String DB_URL = "jdbc:mysql://127.0.0.1/uas?autoReconnect=true&useSSL=false";
    public static final String USER = "root";
    public static final String PASS = "";

    public static Connection conn = null;
    public static Statement stmt;
    public static ResultSet rs;
    /**
     * Creates new form Prestasi
     */
    public Prestasi() {
        initComponents();
        loadData();
        loadData2();
    }
    
    private void loadData() {
    User user = Session.getInstance().getUser();
    if (user == null) {
        System.out.println("User is null in loadData");
        return;
    }
    String id = user.getId();
    System.out.println("Loading data for ID: " + id);

    Connection conn = null;
    try {
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        String sql = "SELECT * FROM nilai_ijazah WHERE id = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, id);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            System.out.println("Data found for ID: " + id);
            txtpendAgama.setText(rs.getString("pendAgama"));
            txtppkn.setText(rs.getString("ppkn"));
            txtbhsIndo.setText(rs.getString("bhsIndo"));
            txtmatematika.setText(rs.getString("matematika"));
            txtsejarah.setText(rs.getString("sejarah"));
            txtbhsInggris.setText(rs.getString("bhsInggris"));
            txtseniBudaya.setText(rs.getString("seniBudaya"));
            txtbhsJawa.setText(rs.getString("bhsJawa"));
            txtbiologi.setText(rs.getString("biologi")); // Corrected from "bilogi"
            txtfisika.setText(rs.getString("fisika"));
            txtkimia.setText(rs.getString("kimia"));

            // Disable fields and enable the edit button
            txtpendAgama.setEnabled(false);
            txtppkn.setEnabled(false);
            txtbhsIndo.setEnabled(false);
            txtmatematika.setEnabled(false);
            txtsejarah.setEnabled(false);
            txtbhsInggris.setEnabled(false);
            txtseniBudaya.setEnabled(false);
            txtbhsJawa.setEnabled(false);
            txtbiologi.setEnabled(false);
            txtfisika.setEnabled(false);
            txtkimia.setEnabled(false);
            btnSimpan1.setEnabled(false);
            btnEdit1.setEnabled(true);
        } else {
            System.out.println("No data found for ID: " + id);

            // Enable fields and disable the edit button
            txtpendAgama.setEnabled(true);
            txtppkn.setEnabled(true);
            txtbhsIndo.setEnabled(true);
            txtmatematika.setEnabled(true);
            txtsejarah.setEnabled(true);
            txtbhsInggris.setEnabled(true);
            txtseniBudaya.setEnabled(true);
            txtbhsJawa.setEnabled(true);
            txtbiologi.setEnabled(true);
            txtfisika.setEnabled(true);
            txtkimia.setEnabled(true);
            btnSimpan1.setEnabled(true);
            btnEdit1.setEnabled(false);
        }

        rs.close();
        ps.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data!");
    } finally {
        try {
            if (conn != null) conn.close();
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtpendAgama = new javax.swing.JTextField();
        txtppkn = new javax.swing.JTextField();
        txtbhsIndo = new javax.swing.JTextField();
        txtbhsInggris = new javax.swing.JTextField();
        txtsejarah = new javax.swing.JTextField();
        txtmatematika = new javax.swing.JTextField();
        txtfisika = new javax.swing.JTextField();
        txtbhsJawa = new javax.swing.JTextField();
        txtseniBudaya = new javax.swing.JTextField();
        txtbiologi = new javax.swing.JTextField();
        btnSimpan1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        txtkimia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPenyelenggara = new javax.swing.JTextField();
        txtNamaKejuaraan = new javax.swing.JTextField();
        txtTingkat = new javax.swing.JComboBox<>();
        txtKategori = new javax.swing.JComboBox<>();
        txtTahun = new javax.swing.JComboBox<>();
        txtJuara = new javax.swing.JComboBox<>();
        btnSimpan2 = new javax.swing.JButton();
        btnEdit2 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Input Nilai Ijazah");

        jLabel3.setText("Sejarah Indonesia");

        jLabel4.setText("Pend. Agama");

        jLabel5.setText("Fisika");

        jLabel6.setText("Biologi");

        jLabel7.setText("Matematika");

        jLabel8.setText("PPKN");

        jLabel9.setText("Bahasa Inggris");

        jLabel10.setText("Bhs Indonesia");

        jLabel11.setText("Seni Budaya");

        jLabel12.setText("Bahasa Jawa");

        txtpendAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpendAgamaActionPerformed(evt);
            }
        });

        txtfisika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfisikaActionPerformed(evt);
            }
        });

        btnSimpan1.setText("Simpan ");
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });

        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        txtkimia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkimiaActionPerformed(evt);
            }
        });

        jLabel13.setText("Kimia");

        jLabel2.setText("Prestasi(Tidak Wajib)");

        jLabel14.setText("Juara");

        jLabel15.setText("Kategori");

        jLabel16.setText("Nama Kejuaraan");

        jLabel17.setText("Tingkat");

        jLabel18.setText("Tahun");

        jLabel19.setText("Penyelenggara");

        txtTingkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Internasional", "Nasional", "Provinsi", "Kabupaten/Kota" }));

        txtKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akademik", "Non Akademik" }));

        txtTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2023", "2022", "2021", "2020" }));

        txtJuara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        btnSimpan2.setText("Simpan");
        btnSimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan2ActionPerformed(evt);
            }
        });

        btnEdit2.setText("Edit");
        btnEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(btnEdit1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpan1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkimia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtfisika, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(txtbiologi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(txtbhsJawa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(txtseniBudaya, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(txtbhsInggris, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(txtsejarah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(txtmatematika, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(txtbhsIndo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(txtppkn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(txtpendAgama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(103, 103, 103)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnSimpan2)
                                                .addGap(41, 41, 41))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel16))
                                                .addGap(52, 52, 52)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtJuara, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtPenyelenggara, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtNamaKejuaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtKategori, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                                        .addComponent(txtTingkat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addComponent(btnEdit2)))))
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(219, 219, 219))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfisika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)
                                        .addGap(21, 21, 21)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPenyelenggara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNamaKejuaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(txtJuara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtpendAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtppkn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtbhsIndo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtmatematika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtsejarah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGap(16, 16, 16)
                                    .addComponent(txtbhsInggris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel9)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtseniBudaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSimpan2)
                                    .addComponent(btnEdit2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbhsJawa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbiologi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkimia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit1)
                    .addComponent(btnSimpan1))
                .addGap(144, 144, 144))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtpendAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpendAgamaActionPerformed
       
    }//GEN-LAST:event_txtpendAgamaActionPerformed

    private void txtfisikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfisikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfisikaActionPerformed

    private void txtkimiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkimiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkimiaActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        User user = Session.getInstance().getUser();
    if (user == null) {
        System.out.println("User is null in btnKirimActionPerformed");
        return;
    }
    String id = user.getId();
    String strPendAgama = txtpendAgama.getText();
    String strPpkn = txtppkn.getText();
    String strBhsIndo = txtbhsIndo.getText();
    String strMatematika = txtmatematika.getText();
    String strSejarah = txtsejarah.getText();
    String strBhsInggris = txtbhsInggris.getText();
    String strSeniBudaya = txtseniBudaya.getText();
    String strBhsJawa = txtbhsJawa.getText();
    String strBiologi = txtbiologi.getText();
    String strFisika = txtfisika.getText();
    String strKimia = txtkimia.getText();

    if (id.isEmpty() || strPendAgama.isEmpty() || strPpkn.isEmpty() || strBhsIndo.isEmpty() || strMatematika.isEmpty() || strSejarah.isEmpty()
            || strBhsInggris.isEmpty() || strSeniBudaya.isEmpty() || strBhsJawa.isEmpty() || strBiologi.isEmpty() || strFisika.isEmpty() || strKimia.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua harus di isi");
    } else {
        try {
            int pendAgama = Integer.parseInt(strPendAgama);
            int ppkn = Integer.parseInt(strPpkn);
            int bhsIndo = Integer.parseInt(strBhsIndo);
            int matematika = Integer.parseInt(strMatematika);
            int sejarah = Integer.parseInt(strSejarah);
            int bhsInggris = Integer.parseInt(strBhsInggris);
            int seniBudaya = Integer.parseInt(strSeniBudaya);
            int bhsJawa = Integer.parseInt(strBhsJawa);
            int biologi = Integer.parseInt(strBiologi);
            int fisika = Integer.parseInt(strFisika);
            int kimia = Integer.parseInt(strKimia);

            Class.forName(JDBC_DRIVER);
            try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS)) {

                // Check if the data already exists
                String checkSql = "SELECT COUNT(*) FROM nilai_ijazah WHERE id = ?";
                int count;
                try (PreparedStatement checkPs = conn.prepareStatement(checkSql)) {
                    checkPs.setString(1, id);
                    ResultSet rs = checkPs.executeQuery();
                    rs.next();
                    count = rs.getInt(1);
                }

                String sql;
                if (count > 0) {
                    // Update existing data
                    sql = "UPDATE nilai_ijazah SET pendAgama = ?, ppkn = ?, bhsIndo = ?, matematika = ?, sejarah = ?, bhsInggris = ?, seniBudaya = ?, bhsJawa = ?, biologi = ?, fisika = ?, kimia = ? WHERE id = ?";
                } else {
                    // Insert new data
                    sql = "INSERT INTO nilai_ijazah (id, pendAgama, ppkn, bhsIndo, matematika, sejarah, bhsInggris, seniBudaya, bhsJawa, biologi, fisika, kimia) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                }

                try (PreparedStatement ps = conn.prepareStatement(sql)) {
                    ps.setString(1, id);
                    ps.setInt(2, pendAgama);
                    ps.setInt(3, ppkn);
                    ps.setInt(4, bhsIndo);
                    ps.setInt(5, matematika);
                    ps.setInt(6, sejarah);
                    ps.setInt(7, bhsInggris);
                    ps.setInt(8, seniBudaya);
                    ps.setInt(9, bhsJawa);
                    ps.setInt(10, biologi);
                    ps.setInt(11, fisika);
                    ps.setInt(12, kimia);
                    ps.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
                System.out.println("Data saved for ID: " + id);

                // Disable text fields and button
                setFieldsEnabled(false);
                btnSimpan1.setEnabled(false);
                btnEdit1.setEnabled(true);

            } catch (SQLException se) {
                se.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Masukkan nilai numerik yang valid!");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Driver JDBC tidak ditemukan!");
        }
    }
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void setFieldsEnabled(boolean enabled) {
    txtpendAgama.setEnabled(enabled);
    txtppkn.setEnabled(enabled);
    txtbhsIndo.setEnabled(enabled);
    txtmatematika.setEnabled(enabled);
    txtsejarah.setEnabled(enabled);
    txtbhsInggris.setEnabled(enabled);
    txtseniBudaya.setEnabled(enabled);
    txtbhsJawa.setEnabled(enabled);
    txtbiologi.setEnabled(enabled);
    txtfisika.setEnabled(enabled);
    txtkimia.setEnabled(enabled);
}
    
    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
            txtpendAgama.setEnabled(true);
            txtppkn.setEnabled(true);
            txtbhsIndo.setEnabled(true);
            txtmatematika.setEnabled(true);
            txtsejarah.setEnabled(true);
            txtbhsInggris.setEnabled(true);
            txtseniBudaya.setEnabled(true);
            txtbhsJawa.setEnabled(true);
            txtbiologi.setEnabled(true);
            txtfisika.setEnabled(true);
            txtkimia.setEnabled(true);
            btnEdit1.setEnabled(false);
            btnSimpan1.setEnabled(true);
    }//GEN-LAST:event_btnEdit1ActionPerformed
    
    private void loadData2() {
        User user = Session.getInstance().getUser();
    if (user == null) {
        System.out.println("User is null in loadData");
        return;
    }
    String id = user.getId();
    System.out.println("Loading data for ID: " + id);
    
    try {
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        String sql = "SELECT * FROM prestasi WHERE id = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, id);
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            System.out.println("Data found for ID: " + id);
            txtKategori.setSelectedItem(rs.getString("kategori"));
            txtTingkat.setSelectedItem(rs.getString("tingkat"));
            txtPenyelenggara.setText(rs.getString("penyelenggara"));
            txtNamaKejuaraan.setText(rs.getString("namaKejuaraan"));
            txtJuara.setSelectedItem(rs.getString("juara"));
            txtTahun.setSelectedItem(rs.getString("tahun"));
            
            // Disable fields and enable the edit button
            txtKategori.setEnabled(false);
            txtTingkat.setEnabled(false);
            txtPenyelenggara.setEnabled(false);
            txtNamaKejuaraan.setEnabled(false);
            txtJuara.setEnabled(false);
            txtTahun.setEnabled(false);
            btnSimpan2.setEnabled(false);
            btnEdit2.setEnabled(true);
            
        } else {
            System.out.println("No data found for ID: " + id);
            
            // Enable fields and disable the edit button
            txtKategori.setEnabled(true);
            txtTingkat.setEnabled(true);
            txtPenyelenggara.setEnabled(true);
            txtNamaKejuaraan.setEnabled(true);
            txtJuara.setEnabled(true);
            txtTahun.setEnabled(true);
            btnSimpan2.setEnabled(true);
            btnEdit2.setEnabled(false);
        }
        
        rs.close();
        ps.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data!");
    } finally {
        try {
            if (conn != null) conn.close();
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }
    }
    private void btnSimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan2ActionPerformed
         User user = Session.getInstance().getUser();
    if (user == null) {
        System.out.println("User is null in btnKirimActionPerformed");
        return;
    }
    String id = user.getId();
    String kategori = (String) txtKategori.getSelectedItem();
    String tingkat = (String) txtTingkat.getSelectedItem();
    String penyelenggara = txtPenyelenggara.getText();
    String namaKejuaraan = txtNamaKejuaraan.getText();
    String strJuara = (String) txtJuara.getSelectedItem();
    String tahun = (String) txtTahun.getSelectedItem();

    if (id.isEmpty() || kategori.isEmpty() || tingkat.isEmpty() || penyelenggara.isEmpty() || 
            namaKejuaraan.isEmpty() || strJuara.isEmpty() || tahun.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua harus di isi");
    } else {
        try {
            int juara = Integer.parseInt(strJuara);


            Class.forName(JDBC_DRIVER);
            try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASS)) {

                // Check if the data already exists
                String checkSql = "SELECT COUNT(*) FROM prestasi WHERE id = ?";
                int count;
                try (PreparedStatement checkPs = conn.prepareStatement(checkSql)) {
                    checkPs.setString(1, id);
                    ResultSet rs = checkPs.executeQuery();
                    rs.next();
                    count = rs.getInt(1);
                }

                String sql;
                if (count > 0) {
                    // Update existing data
                    sql = "UPDATE prestasi SET kategori = ?, tingkat = ?, penyelenggara = ?, namaKejuaraan = ?, juara = ?, tahun = ? WHERE id = ?";
                } else {
                    // Insert new data
                    sql = "INSERT INTO prestasi (id, kategori, tingkat, penyelenggara, namaKejuaraan, juara, tahun) VALUES (?, ?, ?, ?, ?, ?, ?)";
                }

                try (PreparedStatement ps = conn.prepareStatement(sql)) {
                    ps.setString(1, id);
                    ps.setString(2, kategori);
                    ps.setString(3, tingkat);
                    ps.setString(4, penyelenggara);
                    ps.setString(5, namaKejuaraan);
                    ps.setInt(6, juara);
                    ps.setString(7, tahun);
                    ps.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
                System.out.println("Data saved for ID: " + id);

                // Disable text fields and button
                txtKategori.setEnabled(false);
                txtTingkat.setEnabled(false);
                txtPenyelenggara.setEnabled(false);
                txtNamaKejuaraan.setEnabled(false);
                txtJuara.setEnabled(false);
                txtTahun.setEnabled(false);
                btnSimpan2.setEnabled(false);
                btnEdit2.setEnabled(true);

            } catch (SQLException se) {
                se.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Masukkan nilai numerik yang valid!");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Driver JDBC tidak ditemukan!");
        }
   }
    }//GEN-LAST:event_btnSimpan2ActionPerformed

    private void btnEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit2ActionPerformed
        txtKategori.setEnabled(true);
            txtTingkat.setEnabled(true);
            txtPenyelenggara.setEnabled(true);
            txtNamaKejuaraan.setEnabled(true);
            txtJuara.setEnabled(true);
            txtTahun.setEnabled(true);
            btnSimpan2.setEnabled(true);
            btnEdit2.setEnabled(false);
        
    }//GEN-LAST:event_btnEdit2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnEdit2;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JButton btnSimpan2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> txtJuara;
    private javax.swing.JComboBox<String> txtKategori;
    private javax.swing.JTextField txtNamaKejuaraan;
    private javax.swing.JTextField txtPenyelenggara;
    private javax.swing.JComboBox<String> txtTahun;
    private javax.swing.JComboBox<String> txtTingkat;
    private javax.swing.JTextField txtbhsIndo;
    private javax.swing.JTextField txtbhsInggris;
    private javax.swing.JTextField txtbhsJawa;
    private javax.swing.JTextField txtbiologi;
    private javax.swing.JTextField txtfisika;
    private javax.swing.JTextField txtkimia;
    private javax.swing.JTextField txtmatematika;
    private javax.swing.JTextField txtpendAgama;
    private javax.swing.JTextField txtppkn;
    private javax.swing.JTextField txtsejarah;
    private javax.swing.JTextField txtseniBudaya;
    // End of variables declaration//GEN-END:variables
}
